# Generated by Django 2.2.19 on 2021-03-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(verbose_name='ID юзера')),
                ('name', models.TextField(verbose_name='Имя юзера')),
            ],
            options={
                'verbose_name': 'Профиль',
            },
        ),
    ]
